### ISSUE TITLE
Is it possible to get access to documentation or white paper or technical paper?

### ISSUE THREAD

**Issue by amyjohansson1994** [uos/ceres_robot#3]
Hi,
Thanks for sharing the project. I am trying to read through and understand the usage of the smach scripts inside ceres_navigation package. I was wondering if there's any documentation you can share.

Thank you

**Comment by juliangaal** [comment]
hey, you might be interested in [these tutorials](https://uos.github.io/mbf_docs/tutorials/advanced/overview/). However: SMACH is unmaintained. Have a look at the alternatives mentoned on the site I just linked.
